name: Issue Open Action

on:
  issues:
    types: [opened, edited]
#on:
#push:
#branches: 'gnmeyer-patch'
jobs:
  edit_issue_title_and_assignees:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} #gets the current repo
          ref: ${{ github.ref }} #gets the current branch
          token: ${{ secrets.EF_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: |
          node scripts/edit-issue ${{ github.repository }} ${{ github.events.issue.number }} ${{ secrets.REPO_ID }} ${{ github.event.issue.title }}
        env:
          TOKEN: ${{ secrets.EF_TOKEN }}
