name: Issue Open Action

#on:
#issues:
#types: [closed]
on:
  push:
    branches: 'gnmeyer-patch'
jobs:
  edit_issue_title_and_assignees:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} #gets the current repo
          ref: ${{ github.ref }} #gets the current branch
          token: ${{ secrets.EF_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: |
          node scripts/edit-issue ${{ github.repository }} 72 ${{ secrets.REPO_ID }} newtitle+a{meher-liatrio}
        env:
          TOKEN: ${{ secrets.EF_TOKEN }}
