name: Display Pull Request Info
on: [workflow_dispatch, pull_request]

jobs:
  get_pull_request_info:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} #gets the current repo
          ref: ${{ github.ref }} #gets the current branch
          token: ${{ secrets.EF_TOKEN2 }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18' #necessary version for graphql
          cache: npm #caches dependencies

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: |
          echo "$(node scripts/get-pull-requests.js)" > scripts/pull_requests.csv
        env: #creates environment variable for js module
          TOKEN: ${{ secrets.EF_TOKEN2 }}

      - name: Debug
        run: |
          cat scripts/pull_requests.csv

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pull_request_info
          path: scripts/pull_requests.csv

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pull_request_info
          path: scripts/pull_requests_info.csv

  update-demo-pr-data:
    runs-on: ubuntu-latest
    needs: get_pull_request_info
    steps:
      - name: Download csv
        uses: actions/download-artifact@v4
        with:
          name: pull_request_info

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: engaging-finches/demo-pr-data
          ref: main
          token: ${{ secrets.PAT }}

      - name: Set Upstream Branch
        run: |
          git pull
          git checkout main

      - name: Update Existing File
        run: |
          # Set up Git configuration 
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"

          # Modify the existing file or replace it with the updated content
          cat pull_requests.csv > README.md

          # Add, commit, and push the changes to the repository
          git add README.md
          git commit -m "Update README"
          git push https://engaging-finches@github.com/engaging-finches/demo-pr-data.git main
