name: Display Pull Request Info
on: 
  [push, pull_request, workflow_dispatch]
      
jobs:
  #checkout the repo
  #setup node
  #install dependencies
  #run module
  #get csv output from module
  #upload csv as artifact

  #need to modify the secrets
  get_pull_request_info:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} #gets the current repo
          ref: ${{ github.ref }} #gets the current branch
          token: ${{ secrets.EF_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
          cache: npm

      - name: Install dependencies
        run: npm install octokit

      - name: Run script
        run: |
          node .github/actions-scripts/use-the-api.mjs
        env:
          TOKEN: ${{ secrets.EF_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pull_request_info
          path: pull_request_info.csv
